EMAIL_SMTP_SERVER = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
EMAIL_USER = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
EMAIL_PASSWORD = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

FROM_EMAIL = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
TO_EMAIL = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

TWITTER_BEARER_TOKEN = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

TWITTER_ID = 000000000000
MAX_RESULTS = 50
MINUTES_TO_CHECK_FEEDS = 15
SECONDS_BETWEEN_REQUEST = 1
